def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('about', '/about')
    config.add_route('qrcode', '/qrcode/{uri}')
    config.add_route('view_raw', '/view/raw/{pasteID}')
    config.add_route('view_embed', '/view/embed/{pasteID}')
    config.add_route('view_paste', '/view/{pasteID}')
    config.add_route('register', '/user/register')
    config.add_route('forgot', '/user/forgot')
    config.add_route('signin', '/user/signin')
    config.add_route('signout', '/user/signout')
    config.add_route('reset_password', '/user/reset/{resetToken}')
    config.add_route('schedeuled_remove', '/cron/{cronkey}')
    config.add_route('api_langs', '/api/langs')
    config.add_route('api_intro', '/api/intro')
    config.add_route('api_get', '/api/{pasteid}')
    config.add_route('api_post', '/api')
