expireTimes = [
    ('0', 'Keep Forever'),
    ('300', '5 Minutes'),
    ('3600', '1 Hour'),
    ('86400', '1 Day'),
    ('604800', '1 Week')
]

encryptionMethods = [
    ('no', 'No Encryption'),
    ('passwd', 'Encrypt with Password'),
    ('pgp', 'Encrypt with PGP Keys')
]

languagesList = [
    ('abap' , 'Abap' ),
    ('abc' , 'Abc' ),
    ('actionscript' , 'Actionscript' ),
    ('ada' , 'Ada' ),
    ('apache_conf' , 'Apache_conf' ),
    ('applescript' , 'Applescript' ),
    ('asciidoc' , 'Asciidoc' ),
    ('assembly_x86' , 'Assembly_x86' ),
    ('autohotkey' , 'Autohotkey' ),
    ('batchfile' , 'Batchfile' ),
    ('c9search' , 'C9search' ),
    ('c_cpp' , 'C++' ),
    ('cirru' , 'Cirru' ),
    ('clojure' , 'Clojure' ),
    ('cobol' , 'Cobol' ),
    ('coffee' , 'Coffee' ),
    ('coldfusion' , 'Coldfusion' ),
    ('csharp' , 'Csharp' ),
    ('css' , 'Css' ),
    ('curly' , 'Curly' ),
    ('d' , 'D' ),
    ('dart' , 'Dart' ),
    ('diff' , 'Diff' ),
    ('django' , 'Django' ),
    ('dockerfile' , 'Dockerfile' ),
    ('dot' , 'Dot' ),
    ('eiffel' , 'Eiffel' ),
    ('ejs' , 'Ejs' ),
    ('elixir' , 'Elixir' ),
    ('elm' , 'Elm' ),
    ('erlang' , 'Erlang' ),
    ('forth' , 'Forth' ),
    ('ftl' , 'Ftl' ),
    ('gcode' , 'Gcode' ),
    ('gherkin' , 'Gherkin' ),
    ('gitignore' , 'Gitignore' ),
    ('glsl' , 'Glsl' ),
    ('golang' , 'Golang' ),
    ('groovy' , 'Groovy' ),
    ('haml' , 'Haml' ),
    ('handlebars' , 'Handlebars' ),
    ('haskell' , 'Haskell' ),
    ('haxe' , 'Haxe' ),
    ('html' , 'Html' ),
    ('html_elixir' , 'Html_elixir' ),
    ('html_ruby' , 'Html_ruby' ),
    ('ini' , 'Ini' ),
    ('io' , 'Io' ),
    ('jack' , 'Jack' ),
    ('jade' , 'Jade' ),
    ('java' , 'Java' ),
    ('javascript' , 'Javascript' ),
    ('json' , 'Json' ),
    ('jsoniq' , 'Jsoniq' ),
    ('jsp' , 'Jsp' ),
    ('jsx' , 'Jsx' ),
    ('julia' , 'Julia' ),
    ('latex' , 'Latex' ),
    ('lean' , 'Lean' ),
    ('less' , 'Less' ),
    ('liquid' , 'Liquid' ),
    ('lisp' , 'Lisp' ),
    ('live_script' , 'Live_script' ),
    ('livescript' , 'Livescript' ),
    ('logiql' , 'Logiql' ),
    ('lsl' , 'Lsl' ),
    ('lua' , 'Lua' ),
    ('luapage' , 'Luapage' ),
    ('lucene' , 'Lucene' ),
    ('makefile' , 'Makefile' ),
    ('markdown' , 'Markdown' ),
    ('mask' , 'Mask' ),
    ('matlab' , 'Matlab' ),
    ('maze' , 'Maze' ),
    ('mel' , 'Mel' ),
    ('mips_assembler' , 'Mips_assembler' ),
    ('mipsassembler' , 'Mipsassembler' ),
    ('mushcode' , 'Mushcode' ),
    ('mysql' , 'Mysql' ),
    ('nix' , 'Nix' ),
    ('objectivec' , 'Objectivec' ),
    ('ocaml' , 'Ocaml' ),
    ('pascal' , 'Pascal' ),
    ('perl' , 'Perl' ),
    ('pgsql' , 'Pgsql' ),
    ('php' , 'Php' ),
    ('plain_text' , 'Plain_text' ),
    ('powershell' , 'Powershell' ),
    ('praat' , 'Praat' ),
    ('prolog' , 'Prolog' ),
    ('properties' , 'Properties' ),
    ('protobuf' , 'Protobuf' ),
    ('python' , 'Python' ),
    ('r' , 'R' ),
    ('rdoc' , 'Rdoc' ),
    ('rhtml' , 'Rhtml' ),
    ('ruby' , 'Ruby' ),
    ('rust' , 'Rust' ),
    ('sass' , 'Sass' ),
    ('scad' , 'Scad' ),
    ('scala' , 'Scala' ),
    ('scheme' , 'Scheme' ),
    ('scss' , 'Scss' ),
    ('sh' , 'Sh' ),
    ('sjs' , 'Sjs' ),
    ('smarty' , 'Smarty' ),
    ('snippets' , 'Snippets' ),
    ('soy_template' , 'Soy_template' ),
    ('space' , 'Space' ),
    ('sql' , 'Sql' ),
    ('sqlserver' , 'Sqlserver' ),
    ('stylus' , 'Stylus' ),
    ('svg' , 'Svg' ),
    ('swift' , 'Swift' ),
    ('swig' , 'Swig' ),
    ('tcl' , 'Tcl' ),
    ('tex' , 'Tex' ),
    ('text' , 'Text' ),
    ('textile' , 'Textile' ),
    ('toml' , 'Toml' ),
    ('twig' , 'Twig' ),
    ('typescript' , 'Typescript' ),
    ('vala' , 'Vala' ),
    ('vbscript' , 'Vbscript' ),
    ('velocity' , 'Velocity' ),
    ('verilog' , 'Verilog' ),
    ('vhdl' , 'Vhdl' ),
    ('xml' , 'Xml' ),
    ('xquery' , 'Xquery' ),
    ('yaml' , 'Yaml' )
]
